#!/bin/bash
transition_type=wave # fade, wipe, grow, outer, random, wave

if [ $# -ne 1 ]; then
  echo "Ошибка: не указана директория"
  exit 1
fi

DIR=$1

if [ ! -d "$DIR" ]; then
  echo "Ошибка: директория '$DIR' не существует"
  exit 1
fi

FILES=("$DIR"/*)

if [ ${#FILES[@]} -eq 0 ]; then
  echo "Ошибка: директория '$DIR' пуста"
  exit 1
fi

RANDOM_BG=${FILES[$RANDOM % ${#FILES[@]}]}
swww img --transition-type="$transition_type" --transition-fps=60 "$RANDOM_BG"
